branch-defaults:
  master:
    environment: TboltWebService
environment-defaults:
  TboltWebService-env:
    branch: master
    repository: origin
global:
  application_name: TBolt Web Service
  default_ec2_keyname: tboltservice
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/PHP 7.2 running on
    64bit Amazon Linux/2.8.12
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
